name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env: # Or as an environment variable
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        working-directory: ./openrct2
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.pkg.github.com
        docker build --file Dockerfile --tag docker.pkg.github.com/andrewmichaelsmith/misc/openrct2:latest .
        docker push docker.pkg.github.com/andrewmichaelsmith/misc/openrct2:latest

